#pragma once

/* Serial settings */
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SPLIT_HAND_PIN      GP29
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_WATCHDOG_ENABLE

/* split protocol settings */
#define SELECT_SOFT_SERIAL_SPEED 1
#define SPLIT_TRANSACTION_IDS_USER RPC_SYNC_CONFIG, RPC_SYNC_HID

#define TAP_CODE_DELAY 1

#define EH_SHORT_PRODUCT_NAME "I44"

#define ORBITAL_MOUSE_SPEED_CURVE \
      {25, 30, 44, 69, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99}
