# Load Xresources
xrdb $HOME/.config/X11/Xresources

# Set keyboard to my custom config
kmonad -w 0 $HOME/.config/keyboard/colex.kbd &

# Locking system
xautolock -time 1 -corners 000- -locker slock &

# Set the bar to show the date
dwmblocks &

# Clipboard deamon
clipmenud &

# Compositor
picom --experimental-backends --config $HOME/.config/picom.conf -b

# Set the desktop wallpaper (custom scirpt)
setwall &

# Run the desktop
exec dbus-launch dwm
