prompt = ''

padding = 100

fonts = [ 'Jet Brains Mono' ]
font_size = 72.0

[history]
decrease_interval = 48

[colors]
background = '#000000'
prompt = '#abb2bfff'
text = '#ffffffff'
text_query = '#e5c07bff'
text_selected = '#61afefff'

[keybindings]
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["KP_Delete", "Delete", "BackSpace"]
delete_word = ["ctrl+KP_Delete", "ctrl+Delete", "ctrl+BackSpace"]
complete = ["Tab"]
nav_up = ["Up"]
nav_down = ["Down"]
exit = ["Escape"]
