- name: Install the package
  package:
    name: neovim
    state: latest
- name: Place the configs
  git:
    repo: 'git@github.com:veyxov/nvim.git'
    dest: '~/.config/nvim'
    key_file: "~/.ssh/id_rsa"
    accept_hostkey: yes
