RAW_ENABLE = yes

CAPS_WORD_ENABLE = yes
LEADER_ENABLE = yes
BOOTMAGIC_ENABLE = yes

MOUSE_ENABLE = yes

EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
TAP_DANCE_ENABLE = yes

COMBO_ENABLE = yes
VPATH += keyboards/gboards

DYNAMIC_MACRO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
