AUTO_SHIFT_ENABLE = no
COMMAND_ENABLE = no
AUTOCORRECT_ENABLE = no
CAPS_WORD_ENABLE = yes


ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no

CONSOLE_ENABLE = yes

LEADER_ENABLE = yes
NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
LTO_ENABLE = no
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
NO_USB_STARTUP_CHECK = no

WPM_ENABLE = no
RAW_ENABLE = no

UNICODE_COMMON = yes
UNICODE_ENABLE = yes
