#!/bin/sh

riverctl keyboard-layout -options "grp:win_space_toggle" "us,rus"

riverctl map normal Super F toggle-fullscreen # full screen
riverctl map normal Super u spawn kickoff # app menu
riverctl map normal Super s spawn 'grim -g "$(slurp -d)" - | wl-copy' # screenshot
riverctl map normal Super Q close # close
riverctl map normal Super H focus-view previous # focus prev
riverctl map normal Super+Shift H swap next # swap next

riverctl map normal Super Comma focus-output previous # next screen
riverctl map normal Super+Shift Comma send-to-output previous # send to next screen

# Super+K and Super+J to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super k send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super j send-layout-cmd rivertile "main-ratio +0.05"

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    #riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    #riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl border-color-focused 0x03346E
riverctl border-color-unfocused 0x021526

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

riverctl set-cursor-warp on-output-change

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# core
riverctl spawn "swayidle -w timeout 30 'swaylock -c 111111' before-sleep 'swaylock -c 111111'"
riverctl spawn "setwall"

# services
riverctl spawn 'playerctld daemon'
riverctl spawn 'mako'
riverctl spawn 'sudo ~/.local/bin/kanata/target/release/kanata -n -c ~/.config/keyboard/config > ~/kanata.log'

# clipboard manager
riverctl spawn 'wl-paste --watch cliphist store'
riverctl map normal Super p spawn 'cliphist list | kickoff --from-stdin --stdout | cliphist decode | wl-copy'

# apps
riverctl spawn 'telegram-desktop'
riverctl spawn 'firefox'
