#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox:Navigator desktop='^1' follow=on
bspc rule -a Alacritty desktop='^2' state=fullscreen follow=on
bspc rule -a TelegramDesktop desktop='^5' state=fullscreen follow=on

firefox &
telegram-desktop &
alacritty &
