#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI1 -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

firefox &
telegram-desktop &
alacritty &
