"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000
palette = 'rose_pine'

format = """$directory$git_branch$git_status$nodejs$rust$dotnet$cmd_duration$character"""

[character]
success_symbol = '[❯](bold green)'

[directory]
truncation_length = 4
style = 'bold foam'

[git_branch]
symbol = ' '
style = 'bold iris'

[git_status]
style = 'bold gold'

[palettes.rose_pine]
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
text = '#e0def4'
subtle = '#908caa'
muted = '#6e6a86'
highlight_high = '#524f67'
highlight_med = '#403d52'
highlight_low = '#21202e'
overlay = '#26233a'
surface = '#1f1d2e'
base = '#191724'

[nodejs]
symbol = ' '
format = '[$symbol($version )]($style)'

[rust]
symbol = ' '
format = '[$symbol($version )]($style)'

[dotnet]
symbol = '.NET '
format = '[$symbol($version )]($style)'

[cmd_duration]
min_time = 2000
format = 'took [$duration]($style) '
