"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000
palette = 'catppuccin_mocha'

format = """$directory$git_branch$git_status$nodejs$rust$dotnet$cmd_duration$character"""

[character]
success_symbol = '[❯](bold green)'

[directory]
truncation_length = 4
style = 'bold blue'

[git_branch]
symbol = ' '
style = 'bold mauve'

[git_status]
style = 'bold yellow'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[nodejs]
symbol = ' '
format = '[$symbol($version )]($style)'

[rust]
symbol = ' '
format = '[$symbol($version )]($style)'

[dotnet]
symbol = '.NET '
format = '[$symbol($version )]($style)'

[cmd_duration]
min_time = 2000
format = 'took [$duration]($style) '
