include ./themes/brogramer.conf

input_delay 0
repaint_delay 2
sync_to_monitor no
wayland_enable_ime no
background_opacity 0.85

allow_remote_control socket-only
listen_on unix:/tmp/kitty
shell_integration enabled

enabled_layouts splits

shell fish
editor nvim

font_family      Maple Mono NF
font_size 24.0
hide_window_decorations yes

scrollback_pager nvim -

clear_all_shortcuts no
kitty_mod alt
map kitty_mod+p scroll_to_prompt -1
map kitty_mod+f scroll_to_prompt 1
map kitty_mod+t set_tab_title
map kitty_mod+_ close_window

map kitty_mod+i open_url_with_hints

map kitty_mod+n new_tab_with_cwd

map kitty_mod+a previous_tab
map kitty_mod+e next_tab

map kitty_mod+l next_window

map ctrl+backspace send_text all \x17

map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard

map kitty_mod+slash  change_font_size all +2.0
map kitty_mod+shift+slash  change_font_size all -2.0

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten /home/iz/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py

# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output


map kitty_mod+d launch --location=hsplit --cwd=current
map kitty_mod+s launch --location=vsplit

map kitty_mod+o scroll_page_down
map kitty_mod+y scroll_page_up
map kitty_mod+u scroll_end

map kitty_mod+space select_tab


cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
