# theme: swap the include to themes/rose-pine-dawn.conf for light mode
include themes/rose-pine.conf

background_opacity 0.85
background_blur 20

font_family FantasqueSansM Nerd Font Mono
font_size 16
font_thicken

macos_option_as_alt yes
macos_titlebar_color background
hide_window_decorations yes
confirm_os_window_close 0
macos_quit_when_last_window_closed yes

enabled_layouts splits
editor nvim
allow_remote_control socket-only
listen_on unix:/tmp/kitty-scrollback-nvim

action_alias kitty_scrollback_nvim kitty +kitten ~/.local/share/nvim/site/pack/core/opt/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py

kitty_mod alt

map kitty_mod+p scroll_to_prompt -1
map kitty_mod+f scroll_to_prompt 1
map kitty_mod+h set_tab_title

map kitty_mod+i open_url_with_hints

map kitty_mod+n new_tab_with_cwd
map kitty_mod+x close_window
map kitty_mod+z toggle_layout stack

map kitty_mod+a previous_tab
map kitty_mod+e next_tab

map kitty_mod+l next_window

map ctrl+backspace send_text all \x17
map alt+backspace send_text all \x17

map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard

map kitty_mod+slash change_font_size all +2.0
map kitty_mod+shift+slash change_font_size all -2.0

map kitty_mod+t kitty_scrollback_nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output

map kitty_mod+d launch --location=hsplit --cwd=current
map kitty_mod+s launch --location=vsplit

map kitty_mod+o scroll_page_down
map kitty_mod+y scroll_page_up
map kitty_mod+u scroll_end

map kitty_mod+space select_tab

map kitty_mod+Enter no_op
