gui:
  skipAmendWarning: true
  showRootItemInFileTree: false
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#c4a7e7"
      - bold
    inactiveBorderColor:
      - "#6e6a86"
    optionsTextColor:
      - "#9ccfd8"
    selectedLineBgColor:
      - "#1f1d2e"
    cherryPickedCommitBgColor:
      - "#26233a"
    cherryPickedCommitFgColor:
      - "#c4a7e7"
    unstagedChangesColor:
      - "#eb6f92"
    defaultFgColor:
      - "#e0def4"
    searchingActiveBorderColor:
      - "#f6c177"

update:
  method: never
keybinding:
  universal:
    quit: [<esc>]
    return: <ctrl+x>

git:
  overrideGpg: true
